services:
  - type: web
    name: rest-api-project
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generator: secret
      - key: DATABASE_URL
        fromDatabase: rest-db

databases:
  - name: rest-db
    plan: starter
    region: oregon